const words = [
    "javascript", "discord", "hangman", "minigame", "bot", "programming", "developer", 
    "algorithm", "function", "variable", "constant", "array", "object", "string", 
    "boolean", "number", "null", "undefined", "class", "method", "property", "module", 
    "package", "library", "framework", "frontend", "backend", "fullstack", "database", 
    "query", "server", "client", "network", "protocol", "http", "https", "socket", 
    "api", "json", "xml", "html", "css", "react", "angular", "vue", "svelte", 
    "typescript", "node", "express", "django", "flask", "ruby", "rails", "java", 
    "kotlin", "swift", "objective", "php", "laravel", "golang", "rust", "csharp", 
    "dotnet", "unity", "unreal", "game", "engine", "design", "ux", "ui", "testing", 
    "jest", "mocha", "chai", "selenium", "cypress", "puppeteer", "automation", 
    "devops", "docker", "kubernetes", "terraform", "ansible", "jenkins", "github", 
    "gitlab", "bitbucket", "version", "control", "repository", "branch", "merge", 
    "commit", "push", "pull", "clone", "fork", "issue", "pullrequest", "review", 
    "lint", "prettier", "eslint", "debug", "log", "error", "exception", "stack", 
    "trace", "performance", "optimization", "refactor", "clean", "code", "architecture", 
    "pattern", "singleton", "factory", "observer", "strategy", "adapter", "decorator", 
    "proxy", "middleware", "controller", "model", "view", "route", "handler", 
    "request", "response", "status", "header", "body", "cookie", "session", 
    "authentication", "authorization", "encryption", "hashing", "security", 
    "firewall", "antivirus", "malware", "phishing", "ransomware", "trojan", 
    "spyware", "adware", "rootkit", "worm", "botnet", "ddos", "attack", "vulnerability", 
    "patch", "update", "upgrade", "release", "versioning", "semver", "dependency", 
    "management", "npm", "yarn", "pip", "maven", "gradle", "build", "tool", 
    "compiler", "interpreter", "runtime", "virtual", "machine", "container", 
    "cloud", "aws", "azure", "gcp", "digitalocean", "linode", "heroku", "netlify", 
    "vercel", "hosting", "deployment", "ci", "cd", "pipeline", "monitoring", 
    "logging", "metrics", "alerting", "incident", "response", "sla", "uptime", 
    "downtime", "latency", "bandwidth", "throughput", "scalability", "availability",
    "kitchen", "bedroom", "bathroom", "livingroom", "diningroom", "garage", 
    "garden", "balcony", "basement", "attic", "pantry", "closet", "sofa", 
    "table", "chair", "lamp", "bed", "pillow", "blanket", "curtain", "carpet", 
    "rug", "mirror", "shelf", "cabinet", "drawer", "stove", "oven", "microwave", 
    "refrigerator", "freezer", "sink", "faucet", "dishwasher", "toaster", 
    "blender", "mixer", "kettle", "coffee", "teapot", "plate", "bowl", "cup", 
    "glass", "spoon", "fork", "knife", "napkin", "towel", "soap", "shampoo", 
    "toothbrush", "toothpaste", "comb", "brush", "laundry", "basket", "iron", 
    "vacuum", "broom", "mop", "bucket", "detergent", "trash", "bin", "recycling", 
    "clock", "calendar", "photo", "frame", "vase", "plant", "flower", "candle", 
    "fireplace", "heater", "fan", "airconditioner", "remote", "television", 
    "radio", "speaker", "computer", "laptop", "tablet", "phone", "charger", 
    "lightbulb", "switch", "outlet", "extension", "cord", "battery", "toolbox", 
    "hammer", "screwdriver", "wrench", "pliers", "drill", "nails", "screws", 
    "tape", "glue", "paint", "brushes", "ladder", "bucket", "hose", "sprinkler", 
    "lawnmower", "rake", "shovel", "wheelbarrow", "seed", "fertilizer", "pesticide"
];

module.exports = words;
